name: wind-energy
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy=1.20.2
  - pandas=1.2.3
  - xarray=0.17.0
  - netCDF4=1.5.6
  - cartopy=0.18.0
  - cmocean=2.0
  - geopandas=0.9.0
  - windrose=1.6.8
  - scikit-learn=0.24.2
  - geographiclib=1.52
  - metpy=1.1
  - wrf-python=1.3.2
